name : EnergyAlternativesPlaning
channels:
  - conda-forge
  - defaults
dependencies :
    - pandas
    - numpy
    - pip :
      - pyomo
      - Mosek
      - plotly
      - matplotlib==3.5.2
      - sklearn
      - mycolorpy

