name : PlaninModel_env
channels:
  - conda-forge
  - defaults
dependencies :
    - jupyter
    - pip
    - scipy
    - openpyxl
    - pip :
      - gurobipy
      - openpyxl
      - scikit-learn
      - seaborn
      - EnergyAlternativesPlaning

