name : energyalternatives
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies :
    - python>=3.10
    - pandas
    - jupyter
    - numpy
    - cython
    - pytest
    - pip
    - glpk
    - seaborn
    - qgrid
    - pip :
      - pyomo
      - Mosek
      - xarray
      - plotly
      - matplotlib
      - sklearn

