name : energyalternatives
channels:
  - conda-forge
  - defaults
dependencies :
    - python>=3.10
    - pandas
    - jupyter
    - numpy
    - pytest
    - pip
    - glpk
    - seaborn
    - qgrid
    - openpyxl
    - nb_conda
    - pip :
      - pyomo
      - Mosek
      - xarray
      - plotly
      - matplotlib
      - sklearn
      - mycolorpy

